name <- readline(prompt = "Enter your name: ")
cat("Your name is:", name, "\n")
age <- as.numeric(readline(prompt = "Enter your age: "))
cat("Your age is:", age, "\n")
cat("Enter numeric values separated by space: ")
numeric_data <- scan(what = numeric(), quiet = TRUE)
print(numeric_data)
cat("Enter characters separated by space: ")
char_data <- scan(what = character(), quiet = TRUE)
print(char_data)
cat("Enter integer values separated by space: ")
int_data <- scan(what = integer(), quiet = TRUE)
print(int_data)

