num_vec <- c(1.5, 2.3, 4.8)
char_vec <- c("apple", "banana", "cherry")
log_vec <- c(TRUE, FALSE, TRUE)
print(num_vec)
print(typeof(num_vec))
print(char_vec)
print(typeof(char_vec))
print(log_vec)
print(typeof(log_vec))